version: '3.4'

services:
  nodejs_mongo_docker:
      image: nodejs_mongo_docker
      build: .
      environment:
        NODE_ENV: production
      ports:
        - 5000:5000
      volumes:
        - .:/usr/src/app
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: qwerty
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: qwerty
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  data: